packaging_format = 2

id = "khatru-pyramid"
name = "Khatru Pyramid"
description.en = "Nostr invite relay"
description.fr = "Nostr relais d'invitation"

version = "0.1.0~ynh1"

maintainers = ["tijlxyz"]

[upstream]
license = "Unlicense"
code = "https://github.com/github-tijlxyz/khatru-pyramid"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "100M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.relay_name]
    ask.en = "Name for the relay"
    ask.fr = "Nom du relais"
    type = "string"

    [install.relay_pubkey]
    ask.en = "Pubkey for the relay (your Nostr hex pubkey)"
    ask.fr = "Clé publique pour le relais (votre clé publique hexadécimale Nostr)"
    type = "string"

[resources]

    [resources.sources.main]
    url = "https://github.com/github-tijlxyz/khatru-pyramid/archive/refs/tags/v0.1.0.tar.gz"
    sha256 = "de33acc2d224ac8824a61f1b6a9deed382321e26804de9a4397800033092a5e1"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]
    main.default = 3334

    [resources.permissions]
    main.url = "/"
