packaging_format = 2

id = "khatru-pyramid"
name = "Khatru Pyramid"
description.en = "Nostr invite relay"

version = "0.0.5~ynh1"

maintainers = ["tijlxyz"]

[upstream]
license = "Unlicense"
code = "https://github.com/github-tijlxyz/khatru-pyramid"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = [ "amd64" ]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "100M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.relay_name]
    ask.en = "Name for the relay"
    type = "string"

    [install.relay_pubkey]
    ask.en = "Pubkey for the relay (your nostr hex pubkey)"
    type = "string"

[resources]

    [resources.sources.main]
    extract = false
    rename = "khatru-pyramid-bin"
    amd64.url = "https://github.com/github-tijlxyz/khatru-pyramid/releases/download/v0.0.5/khatru-pyramid-v0.0.5-linux-amd64"
    amd64.sha256 = "4c945549c9ef25284d9453557aab22586bb88a87d5fb6c83e125a9af550f766c"

    autoupdate.asset.amd64 = "^khatru-pyramid-v.*-linux-amd64$"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]
    main.default = 3334

    [resources.permissions]
    main.url = "/"

