packaging_format = 2

id = "khatru-pyramid"
name = "Khatru Pyramid"
description.en = "Nostr invite relay"
description.fr = "Nostr relais d'invitation"

version = "0.2.0~ynh1"

maintainers = ["tijlxyz"]

[upstream]
license = "Unlicense"
code = "https://github.com/github-tijlxyz/khatru-pyramid"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = [ "amd64" ]
multi_instance = false
ldap = false
sso = false
disk = "100M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.relay_name]
    ask.en = "Name for the relay"
    ask.fr = "Nom du relais"
    type = "string"

    [install.relay_pubkey]
    ask.en = "Pubkey for the relay (your nostr hex pubkey)"
    ask.fr = "Clé publique pour le relais (votre clé publique hexadécimale Nostr)"
    type = "string"

[resources]

    [resources.sources.main]
    extract = false
    rename = "khatru-pyramid"
    amd64.url = "https://github.com/github-tijlxyz/khatru-pyramid/releases/download/v0.2.0/khatru-pyramid-v0.2.0-linux-amd64"
    amd64.sha256 = "82cbf4793767de5b1adc4b8b297c505eb3d5438539595ce45f4fd3e19149529f"

    autoupdate.asset.amd64 = "^khatru-pyramid-v.*-linux-amd64$"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]
    main.default = 3334

    [resources.permissions]
    main.url = "/"
