#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression --message="Stopping $app's systemd service..." --weight=1
ynh_systemd_action --service_name="$app" --action="stop" --log_path="/var/log/$app/$app.log"

ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1
ynh_change_url_nginx_config

ynh_script_progression --message="Starting $app's systemd service..." --weight=1
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app.log"

ynh_script_progression --message="Change of URL completed for $app" --last
