#!/bin/bash

source /usr/share/yunohost/helpers

ynh_app_setting_set --app="$app" --key=domain --value="$domain"
ynh_app_setting_set --app="$app" --key=relay_name --value="$relay_name"
ynh_app_setting_set --app="$app" --key=relay_pubkey --value="$relay_pubkey"

relay_maxinvites="3"
relay_description=""
relay_contact=""
relay_icon=""

ynh_app_setting_set --app="$app" --key=relay_maxinvites --value="$relay_maxinvites"
ynh_app_setting_set --app="$app" --key=relay_description --value="$relay_description"
ynh_app_setting_set --app="$app" --key=relay_contact --value="$relay_contact"
ynh_app_setting_set --app="$app" --key=relay_icon --value="$relay_icon"

ynh_script_progression --message="Setting up source files..." --weight=1
ynh_setup_source --dest_dir="$install_dir" 
chown -R $app:$app $install_dir
chmod -R 700 $install_dir

ynh_script_progression --message="Adding $app's configuration files..." --weight=1
ynh_add_config --template='khatru-pyramid.env' --destination="$install_dir/khatru-pyramid.env"

ynh_script_progression --message="Add system configurations" --weight=1
ynh_add_nginx_config
ynh_add_systemd_config
yunohost service add "$app" --description="Khatru Pyramid" --log="/var/log/$app.log"

ynh_script_progression --message="Starting $app's systemd service..." --weight=1
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app.log"

