#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:$app $install_dir
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R 700 $install_dir
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Khatru Pyramid" --log="/var/log/$app/$app.log"

ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

ynh_script_progression "Restoration completed for $app"
