#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

chown -R $app:$app $install_dir
chmood -R 700 $install_dir

ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

### This should be a symetric version of what happens in the install script

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="" --log="/var/log/$app.log"

ynh_restore_file --origin_path="/etc/logrotate.d/$app"

ynh_script_progression --message="Reloading NGINX web server and $app's service..." --weight=1

ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app.log"

ynh_systemd_action --service_name=nginx --action=reload

ynh_script_progression --message="Restoration completed for $app" --last
